// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB37XGExzInWQynFkx-SfJ4UTu6DcYyeEY',
    appId: '1:1077592208390:web:4da2e0a79815ab0ec0bf87',
    messagingSenderId: '1077592208390',
    projectId: 'secondcents',
    authDomain: 'secondcents.firebaseapp.com',
    storageBucket: 'secondcents.appspot.com',
    measurementId: 'G-VBTVKRG7C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzCR5tea1oz20T4Aed9cEaWHYdl0DmldQ',
    appId: '1:1077592208390:android:132f83f564842ce4c0bf87',
    messagingSenderId: '1077592208390',
    projectId: 'secondcents',
    storageBucket: 'secondcents.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4EXuVxEaTbjEu7nVKyucmgOAY9mE_Z8',
    appId: '1:1077592208390:ios:55ee2b652df0a4ffc0bf87',
    messagingSenderId: '1077592208390',
    projectId: 'secondcents',
    storageBucket: 'secondcents.appspot.com',
    iosClientId: '1077592208390-3dmighvl7b65v8dmtspstk1i83e0h3le.apps.googleusercontent.com',
    iosBundleId: 'com.example.twocentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4EXuVxEaTbjEu7nVKyucmgOAY9mE_Z8',
    appId: '1:1077592208390:ios:0b71477b1e91bac0c0bf87',
    messagingSenderId: '1077592208390',
    projectId: 'secondcents',
    storageBucket: 'secondcents.appspot.com',
    iosClientId: '1077592208390-a5vh2urc7pl590gvpdaj5becl9cqf42n.apps.googleusercontent.com',
    iosBundleId: 'com.example.twocentsApp.RunnerTests',
  );
}
