services:
  reverseproxy:
    image: twocents-reverseproxy-image
    build: ./reverseproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverseproxy/conf.d:/etc/nginx/conf.d
      - ./reverseproxy/ssl:/etc/nginx/ssl
      - ./reverseproxy/html:/usr/share/nginx/html
      - ./reverseproxy/logs:/var/log/nginx
    depends_on:
      - server
  server:
    image: twocents-server-image
    build: ./server
    volumes:
      - "./server/src/${FIREBASE_ADMIN_CREDENTIAL_PATH}:/src/${FIREBASE_ADMIN_CREDENTIAL_PATH}"
    env_file:
      - server.env
    expose:
      - "8080"
    ports:
      - "8080:8080"
